### PR TITLE
When setting `ustring` properties to null use `""` instead

### LINKED ISSUE #91: Setting TextView `Text` property to null via 'Del' key in properties goes badly
1. Add a TextView
2. Open properties (F4)
3. Select Text
4. Press Del
5. Confirm setting null

The fix for this would be to set to `""` instead.

```
Failed to set Property
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& argumen
ts, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.InvokeOneParameter(Object obj, Bin
dingFlags invokeAttr, Binder binder, Object parameter, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object valu
e, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo cultu
re)
   at System.Reflection.PropertyInfo.SetValue(Object obj, Object value)
   at TerminalGuiDesigner.ToCode.Property.SetValue(Object value) in /home/ru
nner/work/TerminalGuiDesigner/TerminalGuiDesigner/src/ToCode/Property.cs:lin
e 112
   at TerminalGuiDesigner.Operations.SetPropertyOperation.Do() in /home/runn
er/work/TerminalGuiDesigner/TerminalGuiDesigner/src/Operations/SetPropertyOp
eration.cs:line 143
   at TerminalGuiDesigner.Operations.OperationManager.Do(IOperation op) in /
home/runner/work/TerminalGuiDesigner/TerminalGuiDesigner/src/Operations/Oper
ationManager.cs:line 21
   at TerminalGuiDesigner.UI.Windows.EditDialog.SetProperty(Boolean setNull)
 in /home/runner/work/TerminalGuiDesigner/TerminalGuiDesigner/src/UI/Windows
/EditDialog.cs:line 88
Object reference not set to an instance of an object.
   at Terminal.Gui.TextModel.StringToRunes(ustring content)
   at Terminal.Gui.TextModel.LoadString(ustring content)
   at Terminal.Gui.TextView.set_Text(ustring value)
```

### PR DESCRIPTION
**Pull request by tznind**
Fixes #91

### CODE REVIEW

File: src/ToCode/Property.cs [hunk 1]
```diff
@@ -70,6 +70,13 @@ public virtual void SetValue(object? value)
                     b.Width = s.Length + (b.IsDefault ? 6 : 4);
                 }
             }
+
+            // some views don't like null and only work with "" e.g. TextView
+            // see https://github.com/gui-cs/TerminalGuiDesigner/issues/91
+            if (value == null)
+            {
+                value = ustring.Make("");
+            }
```
Comment (BDisp) [inline src/ToCode/Property.cs:79]: Yes, perhaps there are many bugs on the views that will change it's behavior after I changed the `NStack.ustring.IsNullOrEmpty` method. If there are views that want invalidate for `null` and `empty` theses expressions will fail for the both cases `if (value == null)` or `if (value == "")`. If there are views that want invalidate only for `null` then this expression will fail `if (value == "")`. If there are views that want invalidate only for `empty` then this expression will fail `if (value == null)`. I already changed something in the `TextView` and `TextField` when I fixed the `Clipboard` tests, but I'm certain there are more cases. Your workaround will help in the situations where the views are validate only for empty, but helps a lot. Later the solution is fixing this issues in the views as they come up.

**Review by BDisp — APPROVED** [review]
